### ISSUE TITLE
user checkinTime has not been set

### ISSUE THREAD

**Issue by uduwage** [gallup/NGS2-Router#15]
When looking for time difference exception get thrown since application doesn't set the checkInTime when user initially comes to the router. This should be same are the arrival time. To avoid following exception: 

`java.lang.NullPointerException: null
    at actors.QueueActor.getTimeDifference(QueueActor.java:58)
    at actors.QueueActor.onReceive(QueueActor.java:89)
    at akka.actor.UntypedAbstractActor$$anonfun$receive$1.applyOrElse(AbstractActor.scala:243)
    at akka.actor.Actor$class.aroundReceive(Actor.scala:513)
    at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:132)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
    at akka.actor.ActorCell.invoke(ActorCell.scala:496)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
    at akka.dispatch.Mailbox.run(Mailbox.scala:224)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:234)`

**Comment by disperse** [comment]
This has been fixed.
